# Generated by Django 5.2.5 on 2025-09-02 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='track',
            name='uniq_owner_url',
        ),
        migrations.RemoveIndex(
            model_name='track',
            name='tracks_trac_owner_i_5bb545_idx',
        ),
        migrations.RemoveIndex(
            model_name='track',
            name='tracks_trac_title_78f644_idx',
        ),
        migrations.RemoveField(
            model_name='track',
            name='title',
        ),
        migrations.RemoveField(
            model_name='track',
            name='url',
        ),
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/'),
        ),
        migrations.AddField(
            model_name='track',
            name='name',
            field=models.CharField(default='Untitled Track', max_length=200),
        ),
        migrations.AddField(
            model_name='track',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
