# Generated by Django 5.2.5 on 2025-09-02 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_track_options_remove_track_uniq_owner_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='favorite',
            name='tracks_favo_user_id_f983af_idx',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('owner', 'track')},
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['owner', 'created_at'], name='tracks_favo_owner_i_659563_idx'),
        ),
    ]
