# Generated by Django 5.2.4 on 2025-09-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_remove_favorite_tracks_favo_user_id_f983af_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(default='(untitled)', max_length=200),
        ),
    ]
