# Generated by Django 5.2.5 on 2025-09-13 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_listen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.AddField(
            model_name='favorite',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['owner', 'position'], name='tracks_favo_owner_i_daf432_idx'),
        ),
    ]
