# Generated by Django 5.2.4 on 2025-08-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='period',
            field=models.CharField(default='1 Month', max_length=50),
        ),
    ]
