# Generated by Django 5.2.4 on 2025-09-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_description_alter_plan_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='storage_gb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(default='Life-Time', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
