# Generated by Django 5.2.5 on 2025-09-05 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('tracks', '0005_listen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='album',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='albumtrack',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_tracks', to='album.album'),
        ),
        migrations.AlterField(
            model_name='albumtrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_albums', to='tracks.track'),
        ),
    ]
