# Generated by Django 5.2.4 on 2025-09-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumtrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_items', to='tracks.track'),
        ),
        migrations.AlterUniqueTogether(
            name='albumtrack',
            unique_together={('album', 'track')},
        ),
    ]
