# Generated by Django 5.2.5 on 2025-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_options_album_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumtrack',
            name='custom_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
