# Generated by Django 5.2.5 on 2025-09-13 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_albumtrack_custom_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='album',
            name='album_album_slug_ee32a8_idx',
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['owner', 'order'], name='album_album_owner_i_4d2877_idx'),
        ),
    ]
