--
-- PostgreSQL database dump
--

\restrict Wsws3AjyHrO8TjJHNy7g3KT7lyhY3UKxZalOIyZxVoNp7NfJrFcMKRusArEpq7h

-- Dumped from database version 15.13 (e37678c)
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: neondb_owner
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO neondb_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: neondb_owner
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO neondb_owner;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO neondb_owner;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: album_album; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.album_album (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    description text NOT NULL,
    is_public boolean NOT NULL,
    is_default boolean NOT NULL,
    slug character varying(180) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    "order" integer NOT NULL,
    owner_id integer NOT NULL,
    CONSTRAINT album_album_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.album_album OWNER TO neondb_owner;

--
-- Name: album_album_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.album_album ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.album_album_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: album_albumtrack; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.album_albumtrack (
    id bigint NOT NULL,
    "position" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    custom_name character varying(200),
    album_id bigint NOT NULL,
    track_id bigint NOT NULL,
    CONSTRAINT album_albumtrack_position_check CHECK (("position" >= 0))
);


ALTER TABLE public.album_albumtrack OWNER TO neondb_owner;

--
-- Name: album_albumtrack_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.album_albumtrack ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.album_albumtrack_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO neondb_owner;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO neondb_owner;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO neondb_owner;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO neondb_owner;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO neondb_owner;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO neondb_owner;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: basket_savedbasket; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.basket_savedbasket (
    id bigint NOT NULL,
    session_key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    updated timestamp with time zone NOT NULL,
    user_id integer
);


ALTER TABLE public.basket_savedbasket OWNER TO neondb_owner;

--
-- Name: basket_savedbasket_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.basket_savedbasket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.basket_savedbasket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: basket_savedbasketitem; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.basket_savedbasketitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    basket_id bigint NOT NULL,
    plan_id bigint NOT NULL,
    CONSTRAINT basket_savedbasketitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.basket_savedbasketitem OWNER TO neondb_owner;

--
-- Name: basket_savedbasketitem_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.basket_savedbasketitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.basket_savedbasketitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: checkout_order; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.checkout_order (
    id bigint NOT NULL,
    order_number character varying(32) NOT NULL,
    full_name character varying(50) NOT NULL,
    email character varying(254) NOT NULL,
    phone_number character varying(20),
    country character varying(2),
    postcode character varying(20),
    town_or_city character varying(40),
    street_address1 character varying(80),
    street_address2 character varying(80),
    county character varying(80),
    date timestamp with time zone NOT NULL,
    order_total numeric(10,2) NOT NULL,
    stripe_pid character varying(254) NOT NULL,
    original_basket text NOT NULL,
    user_id integer,
    user_profile_id bigint
);


ALTER TABLE public.checkout_order OWNER TO neondb_owner;

--
-- Name: checkout_order_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.checkout_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.checkout_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: checkout_orderitem; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.checkout_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL,
    order_id bigint NOT NULL,
    plan_id bigint NOT NULL,
    CONSTRAINT checkout_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.checkout_orderitem OWNER TO neondb_owner;

--
-- Name: checkout_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.checkout_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.checkout_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cloud_connect_cloudaccount; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.cloud_connect_cloudaccount (
    id bigint NOT NULL,
    provider character varying(20) NOT NULL,
    label character varying(120) NOT NULL,
    token_json text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.cloud_connect_cloudaccount OWNER TO neondb_owner;

--
-- Name: cloud_connect_cloudaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.cloud_connect_cloudaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cloud_connect_cloudaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cloud_connect_cloudfilemap; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.cloud_connect_cloudfilemap (
    id bigint NOT NULL,
    file_id character varying(200) NOT NULL,
    name character varying(300) NOT NULL,
    mime character varying(100) NOT NULL,
    size bigint,
    etag character varying(200) NOT NULL,
    track_id bigint NOT NULL,
    link_id bigint NOT NULL
);


ALTER TABLE public.cloud_connect_cloudfilemap OWNER TO neondb_owner;

--
-- Name: cloud_connect_cloudfilemap_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.cloud_connect_cloudfilemap ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cloud_connect_cloudfilemap_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cloud_connect_cloudfolderlink; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.cloud_connect_cloudfolderlink (
    id bigint NOT NULL,
    folder_id character varying(200) NOT NULL,
    display_path character varying(500) NOT NULL,
    last_sync timestamp with time zone,
    account_id bigint NOT NULL,
    album_id bigint NOT NULL
);


ALTER TABLE public.cloud_connect_cloudfolderlink OWNER TO neondb_owner;

--
-- Name: cloud_connect_cloudfolderlink_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.cloud_connect_cloudfolderlink ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cloud_connect_cloudfolderlink_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO neondb_owner;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO neondb_owner;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO neondb_owner;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO neondb_owner;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO neondb_owner;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: follow_system_follow; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.follow_system_follow (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    follower_id integer NOT NULL,
    following_id integer NOT NULL,
    CONSTRAINT prevent_self_follow CHECK ((NOT (follower_id = following_id)))
);


ALTER TABLE public.follow_system_follow OWNER TO neondb_owner;

--
-- Name: follow_system_follow_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.follow_system_follow ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.follow_system_follow_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plans_plan; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.plans_plan (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    price numeric(6,2) NOT NULL,
    description text,
    period character varying(50) NOT NULL,
    is_unlimited_tracks boolean NOT NULL,
    is_unlimited_playlists boolean NOT NULL,
    is_unlimited_albums boolean NOT NULL,
    storage_gb integer NOT NULL,
    CONSTRAINT plans_plan_storage_gb_check CHECK ((storage_gb >= 0))
);


ALTER TABLE public.plans_plan OWNER TO neondb_owner;

--
-- Name: plans_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.plans_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plans_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plans_usersubscription; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.plans_usersubscription (
    id bigint NOT NULL,
    start_date timestamp with time zone NOT NULL,
    active boolean NOT NULL,
    plan_id bigint,
    user_id integer NOT NULL
);


ALTER TABLE public.plans_usersubscription OWNER TO neondb_owner;

--
-- Name: plans_usersubscription_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.plans_usersubscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plans_usersubscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: playlist_playlist; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.playlist_playlist (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    owner_id integer NOT NULL
);


ALTER TABLE public.playlist_playlist OWNER TO neondb_owner;

--
-- Name: playlist_playlist_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.playlist_playlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.playlist_playlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: playlist_playlistitem; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.playlist_playlistitem (
    id bigint NOT NULL,
    "position" integer NOT NULL,
    added_at timestamp with time zone NOT NULL,
    playlist_id bigint NOT NULL,
    track_id bigint NOT NULL,
    CONSTRAINT playlist_playlistitem_position_check CHECK (("position" >= 0))
);


ALTER TABLE public.playlist_playlistitem OWNER TO neondb_owner;

--
-- Name: playlist_playlistitem_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.playlist_playlistitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.playlist_playlistitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profile_page_userprofile; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.profile_page_userprofile (
    id bigint NOT NULL,
    profile_image character varying(100),
    bio text,
    contact_number character varying(20),
    website character varying(200),
    default_phone_number character varying(20),
    default_country character varying(2),
    default_postcode character varying(20),
    default_town_or_city character varying(40),
    default_street_address1 character varying(80),
    default_street_address2 character varying(80),
    default_county character varying(80),
    user_id integer NOT NULL
);


ALTER TABLE public.profile_page_userprofile OWNER TO neondb_owner;

--
-- Name: profile_page_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.profile_page_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profile_page_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ratings_albumrating; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.ratings_albumrating (
    id bigint NOT NULL,
    stars smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    album_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT ratings_albumrating_stars_check CHECK ((stars >= 0))
);


ALTER TABLE public.ratings_albumrating OWNER TO neondb_owner;

--
-- Name: ratings_albumrating_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.ratings_albumrating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ratings_albumrating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ratings_trackrating; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.ratings_trackrating (
    id bigint NOT NULL,
    stars smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    track_id bigint NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT ratings_trackrating_stars_check CHECK ((stars >= 0))
);


ALTER TABLE public.ratings_trackrating OWNER TO neondb_owner;

--
-- Name: ratings_trackrating_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.ratings_trackrating ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ratings_trackrating_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: save_system_savedalbum; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.save_system_savedalbum (
    id bigint NOT NULL,
    name_snapshot character varying(200) NOT NULL,
    description_snapshot text NOT NULL,
    saved_at timestamp with time zone NOT NULL,
    original_album_id bigint,
    owner_id integer NOT NULL
);


ALTER TABLE public.save_system_savedalbum OWNER TO neondb_owner;

--
-- Name: save_system_savedalbum_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.save_system_savedalbum ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.save_system_savedalbum_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: save_system_savedtrack; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.save_system_savedtrack (
    id bigint NOT NULL,
    name_snapshot character varying(200) NOT NULL,
    saved_at timestamp with time zone NOT NULL,
    album_id bigint NOT NULL,
    original_track_id bigint,
    owner_id integer NOT NULL
);


ALTER TABLE public.save_system_savedtrack OWNER TO neondb_owner;

--
-- Name: save_system_savedtrack_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.save_system_savedtrack ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.save_system_savedtrack_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialaccount; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.socialaccount_socialaccount (
    id integer NOT NULL,
    provider character varying(200) NOT NULL,
    uid character varying(191) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    extra_data jsonb NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialaccount OWNER TO neondb_owner;

--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.socialaccount_socialaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialapp; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.socialaccount_socialapp (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(40) NOT NULL,
    client_id character varying(191) NOT NULL,
    secret character varying(191) NOT NULL,
    key character varying(191) NOT NULL,
    provider_id character varying(200) NOT NULL,
    settings jsonb NOT NULL
);


ALTER TABLE public.socialaccount_socialapp OWNER TO neondb_owner;

--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.socialaccount_socialapp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialapp_sites; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.socialaccount_socialapp_sites (
    id bigint NOT NULL,
    socialapp_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialapp_sites OWNER TO neondb_owner;

--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.socialaccount_socialapp_sites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_sites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialtoken; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.socialaccount_socialtoken (
    id integer NOT NULL,
    token text NOT NULL,
    token_secret text NOT NULL,
    expires_at timestamp with time zone,
    account_id integer NOT NULL,
    app_id integer
);


ALTER TABLE public.socialaccount_socialtoken OWNER TO neondb_owner;

--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.socialaccount_socialtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tracks_favorite; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tracks_favorite (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    "position" integer NOT NULL,
    owner_id integer NOT NULL,
    track_id bigint NOT NULL,
    CONSTRAINT tracks_favorite_position_check CHECK (("position" >= 0))
);


ALTER TABLE public.tracks_favorite OWNER TO neondb_owner;

--
-- Name: tracks_favorite_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tracks_favorite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tracks_favorite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tracks_listen; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tracks_listen (
    id bigint NOT NULL,
    played_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    track_id bigint NOT NULL
);


ALTER TABLE public.tracks_listen OWNER TO neondb_owner;

--
-- Name: tracks_listen_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tracks_listen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tracks_listen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tracks_track; Type: TABLE; Schema: public; Owner: neondb_owner
--

CREATE TABLE public.tracks_track (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    audio_file character varying(100),
    source_url character varying(200),
    "position" integer NOT NULL,
    play_count integer NOT NULL,
    last_played_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    owner_id integer NOT NULL,
    CONSTRAINT tracks_track_play_count_check CHECK ((play_count >= 0)),
    CONSTRAINT tracks_track_position_check CHECK (("position" >= 0))
);


ALTER TABLE public.tracks_track OWNER TO neondb_owner;

--
-- Name: tracks_track_id_seq; Type: SEQUENCE; Schema: public; Owner: neondb_owner
--

ALTER TABLE public.tracks_track ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tracks_track_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: album_album album_album_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.album_album
    ADD CONSTRAINT album_album_pkey PRIMARY KEY (id);


--
-- Name: album_album album_album_slug_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.album_album
    ADD CONSTRAINT album_album_slug_key UNIQUE (slug);


--
-- Name: album_albumtrack album_albumtrack_album_id_track_id_82f1b7a3_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.album_albumtrack
    ADD CONSTRAINT album_albumtrack_album_id_track_id_82f1b7a3_uniq UNIQUE (album_id, track_id);


--
-- Name: album_albumtrack album_albumtrack_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.album_albumtrack
    ADD CONSTRAINT album_albumtrack_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: basket_savedbasket basket_savedbasket_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.basket_savedbasket
    ADD CONSTRAINT basket_savedbasket_pkey PRIMARY KEY (id);


--
-- Name: basket_savedbasketitem basket_savedbasketitem_basket_id_plan_id_017c5d99_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.basket_savedbasketitem
    ADD CONSTRAINT basket_savedbasketitem_basket_id_plan_id_017c5d99_uniq UNIQUE (basket_id, plan_id);


--
-- Name: basket_savedbasketitem basket_savedbasketitem_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.basket_savedbasketitem
    ADD CONSTRAINT basket_savedbasketitem_pkey PRIMARY KEY (id);


--
-- Name: checkout_order checkout_order_order_number_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.checkout_order
    ADD CONSTRAINT checkout_order_order_number_key UNIQUE (order_number);


--
-- Name: checkout_order checkout_order_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.checkout_order
    ADD CONSTRAINT checkout_order_pkey PRIMARY KEY (id);


--
-- Name: checkout_orderitem checkout_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.checkout_orderitem
    ADD CONSTRAINT checkout_orderitem_pkey PRIMARY KEY (id);


--
-- Name: cloud_connect_cloudaccount cloud_connect_cloudaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.cloud_connect_cloudaccount
    ADD CONSTRAINT cloud_connect_cloudaccount_pkey PRIMARY KEY (id);


--
-- Name: cloud_connect_cloudfilemap cloud_connect_cloudfilemap_link_id_file_id_6c4b9f7d_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.cloud_connect_cloudfilemap
    ADD CONSTRAINT cloud_connect_cloudfilemap_link_id_file_id_6c4b9f7d_uniq UNIQUE (link_id, file_id);


--
-- Name: cloud_connect_cloudfilemap cloud_connect_cloudfilemap_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.cloud_connect_cloudfilemap
    ADD CONSTRAINT cloud_connect_cloudfilemap_pkey PRIMARY KEY (id);


--
-- Name: cloud_connect_cloudfolderlink cloud_connect_cloudfolderlink_album_id_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.cloud_connect_cloudfolderlink
    ADD CONSTRAINT cloud_connect_cloudfolderlink_album_id_key UNIQUE (album_id);


--
-- Name: cloud_connect_cloudfolderlink cloud_connect_cloudfolderlink_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.cloud_connect_cloudfolderlink
    ADD CONSTRAINT cloud_connect_cloudfolderlink_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: follow_system_follow follow_system_follow_follower_id_following_id_ed29d429_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.follow_system_follow
    ADD CONSTRAINT follow_system_follow_follower_id_following_id_ed29d429_uniq UNIQUE (follower_id, following_id);


--
-- Name: follow_system_follow follow_system_follow_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.follow_system_follow
    ADD CONSTRAINT follow_system_follow_pkey PRIMARY KEY (id);


--
-- Name: plans_plan plans_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.plans_plan
    ADD CONSTRAINT plans_plan_pkey PRIMARY KEY (id);


--
-- Name: plans_usersubscription plans_usersubscription_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.plans_usersubscription
    ADD CONSTRAINT plans_usersubscription_pkey PRIMARY KEY (id);


--
-- Name: plans_usersubscription plans_usersubscription_user_id_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.plans_usersubscription
    ADD CONSTRAINT plans_usersubscription_user_id_key UNIQUE (user_id);


--
-- Name: playlist_playlist playlist_playlist_owner_id_name_798f2454_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.playlist_playlist
    ADD CONSTRAINT playlist_playlist_owner_id_name_798f2454_uniq UNIQUE (owner_id, name);


--
-- Name: playlist_playlist playlist_playlist_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.playlist_playlist
    ADD CONSTRAINT playlist_playlist_pkey PRIMARY KEY (id);


--
-- Name: playlist_playlistitem playlist_playlistitem_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.playlist_playlistitem
    ADD CONSTRAINT playlist_playlistitem_pkey PRIMARY KEY (id);


--
-- Name: playlist_playlistitem playlist_playlistitem_playlist_id_track_id_3478ccd1_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.playlist_playlistitem
    ADD CONSTRAINT playlist_playlistitem_playlist_id_track_id_3478ccd1_uniq UNIQUE (playlist_id, track_id);


--
-- Name: profile_page_userprofile profile_page_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.profile_page_userprofile
    ADD CONSTRAINT profile_page_userprofile_pkey PRIMARY KEY (id);


--
-- Name: profile_page_userprofile profile_page_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.profile_page_userprofile
    ADD CONSTRAINT profile_page_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: ratings_albumrating ratings_albumrating_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ratings_albumrating
    ADD CONSTRAINT ratings_albumrating_pkey PRIMARY KEY (id);


--
-- Name: ratings_albumrating ratings_albumrating_user_id_album_id_a0e4f87a_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ratings_albumrating
    ADD CONSTRAINT ratings_albumrating_user_id_album_id_a0e4f87a_uniq UNIQUE (user_id, album_id);


--
-- Name: ratings_trackrating ratings_trackrating_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ratings_trackrating
    ADD CONSTRAINT ratings_trackrating_pkey PRIMARY KEY (id);


--
-- Name: ratings_trackrating ratings_trackrating_user_id_track_id_c74f519f_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ratings_trackrating
    ADD CONSTRAINT ratings_trackrating_user_id_track_id_c74f519f_uniq UNIQUE (user_id, track_id);


--
-- Name: save_system_savedalbum save_system_savedalbum_owner_id_original_album_id_82d11cc4_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.save_system_savedalbum
    ADD CONSTRAINT save_system_savedalbum_owner_id_original_album_id_82d11cc4_uniq UNIQUE (owner_id, original_album_id);


--
-- Name: save_system_savedalbum save_system_savedalbum_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.save_system_savedalbum
    ADD CONSTRAINT save_system_savedalbum_pkey PRIMARY KEY (id);


--
-- Name: save_system_savedtrack save_system_savedtrack_owner_id_original_track__eaf21379_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.save_system_savedtrack
    ADD CONSTRAINT save_system_savedtrack_owner_id_original_track__eaf21379_uniq UNIQUE (owner_id, original_track_id, album_id);


--
-- Name: save_system_savedtrack save_system_savedtrack_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.save_system_savedtrack
    ADD CONSTRAINT save_system_savedtrack_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_provider_uid_fc810c6e_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq UNIQUE (socialapp_id, site_id);


--
-- Name: socialaccount_socialapp socialaccount_socialapp_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.socialaccount_socialapp
    ADD CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp_sites_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id);


--
-- Name: tracks_favorite tracks_favorite_owner_id_track_id_d88805b1_uniq; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tracks_favorite
    ADD CONSTRAINT tracks_favorite_owner_id_track_id_d88805b1_uniq UNIQUE (owner_id, track_id);


--
-- Name: tracks_favorite tracks_favorite_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tracks_favorite
    ADD CONSTRAINT tracks_favorite_pkey PRIMARY KEY (id);


--
-- Name: tracks_listen tracks_listen_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tracks_listen
    ADD CONSTRAINT tracks_listen_pkey PRIMARY KEY (id);


--
-- Name: tracks_track tracks_track_pkey; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tracks_track
    ADD CONSTRAINT tracks_track_pkey PRIMARY KEY (id);


--
-- Name: album_albumtrack uniq_album_position; Type: CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.album_albumtrack
    ADD CONSTRAINT uniq_album_position UNIQUE (album_id, "position");


--
-- Name: account_emailaddress_email_03be32b2; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX account_emailaddress_email_03be32b2 ON public.account_emailaddress USING btree (email);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: album_album_album_i_c302e4_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX album_album_album_i_c302e4_idx ON public.album_albumtrack USING btree (album_id, "position");


--
-- Name: album_album_owner_i_4d2877_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX album_album_owner_i_4d2877_idx ON public.album_album USING btree (owner_id, "order");


--
-- Name: album_album_owner_id_c10e2982; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX album_album_owner_id_c10e2982 ON public.album_album USING btree (owner_id);


--
-- Name: album_album_slug_f7a4afe1_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX album_album_slug_f7a4afe1_like ON public.album_album USING btree (slug varchar_pattern_ops);


--
-- Name: album_albumtrack_album_id_39a93ea6; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX album_albumtrack_album_id_39a93ea6 ON public.album_albumtrack USING btree (album_id);


--
-- Name: album_albumtrack_position_a1782b62; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX album_albumtrack_position_a1782b62 ON public.album_albumtrack USING btree ("position");


--
-- Name: album_albumtrack_track_id_01fed1ce; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX album_albumtrack_track_id_01fed1ce ON public.album_albumtrack USING btree (track_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: basket_savedbasket_session_key_cf1d8753; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX basket_savedbasket_session_key_cf1d8753 ON public.basket_savedbasket USING btree (session_key);


--
-- Name: basket_savedbasket_session_key_cf1d8753_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX basket_savedbasket_session_key_cf1d8753_like ON public.basket_savedbasket USING btree (session_key varchar_pattern_ops);


--
-- Name: basket_savedbasket_user_id_f65b2fc1; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX basket_savedbasket_user_id_f65b2fc1 ON public.basket_savedbasket USING btree (user_id);


--
-- Name: basket_savedbasketitem_basket_id_6d28029d; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX basket_savedbasketitem_basket_id_6d28029d ON public.basket_savedbasketitem USING btree (basket_id);


--
-- Name: basket_savedbasketitem_plan_id_c59761c6; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX basket_savedbasketitem_plan_id_c59761c6 ON public.basket_savedbasketitem USING btree (plan_id);


--
-- Name: checkout_or_date_ab4f50_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX checkout_or_date_ab4f50_idx ON public.checkout_order USING btree (date DESC);


--
-- Name: checkout_or_order_n_88fdbf_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX checkout_or_order_n_88fdbf_idx ON public.checkout_order USING btree (order_number);


--
-- Name: checkout_order_order_number_3d42c998_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX checkout_order_order_number_3d42c998_like ON public.checkout_order USING btree (order_number varchar_pattern_ops);


--
-- Name: checkout_order_user_id_6420a551; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX checkout_order_user_id_6420a551 ON public.checkout_order USING btree (user_id);


--
-- Name: checkout_order_user_profile_id_949184a7; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX checkout_order_user_profile_id_949184a7 ON public.checkout_order USING btree (user_profile_id);


--
-- Name: checkout_orderitem_order_id_b464a9c2; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX checkout_orderitem_order_id_b464a9c2 ON public.checkout_orderitem USING btree (order_id);


--
-- Name: checkout_orderitem_plan_id_ff2838f0; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX checkout_orderitem_plan_id_ff2838f0 ON public.checkout_orderitem USING btree (plan_id);


--
-- Name: cloud_connect_cloudaccount_user_id_f5f6d781; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX cloud_connect_cloudaccount_user_id_f5f6d781 ON public.cloud_connect_cloudaccount USING btree (user_id);


--
-- Name: cloud_connect_cloudfilemap_file_id_b81632b4; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX cloud_connect_cloudfilemap_file_id_b81632b4 ON public.cloud_connect_cloudfilemap USING btree (file_id);


--
-- Name: cloud_connect_cloudfilemap_file_id_b81632b4_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX cloud_connect_cloudfilemap_file_id_b81632b4_like ON public.cloud_connect_cloudfilemap USING btree (file_id varchar_pattern_ops);


--
-- Name: cloud_connect_cloudfilemap_link_id_ada2d592; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX cloud_connect_cloudfilemap_link_id_ada2d592 ON public.cloud_connect_cloudfilemap USING btree (link_id);


--
-- Name: cloud_connect_cloudfilemap_track_id_ad63ff25; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX cloud_connect_cloudfilemap_track_id_ad63ff25 ON public.cloud_connect_cloudfilemap USING btree (track_id);


--
-- Name: cloud_connect_cloudfolderlink_account_id_9fb6f663; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX cloud_connect_cloudfolderlink_account_id_9fb6f663 ON public.cloud_connect_cloudfolderlink USING btree (account_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: follow_syst_followe_17e731_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX follow_syst_followe_17e731_idx ON public.follow_system_follow USING btree (follower_id);


--
-- Name: follow_syst_followi_b7f43b_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX follow_syst_followi_b7f43b_idx ON public.follow_system_follow USING btree (following_id);


--
-- Name: follow_system_follow_follower_id_05bd94c7; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX follow_system_follow_follower_id_05bd94c7 ON public.follow_system_follow USING btree (follower_id);


--
-- Name: follow_system_follow_following_id_bfeb7d58; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX follow_system_follow_following_id_bfeb7d58 ON public.follow_system_follow USING btree (following_id);


--
-- Name: plans_usersubscription_plan_id_8fc03425; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX plans_usersubscription_plan_id_8fc03425 ON public.plans_usersubscription USING btree (plan_id);


--
-- Name: playlist_playlist_owner_id_1072c3f8; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX playlist_playlist_owner_id_1072c3f8 ON public.playlist_playlist USING btree (owner_id);


--
-- Name: playlist_playlistitem_playlist_id_ce173e50; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX playlist_playlistitem_playlist_id_ce173e50 ON public.playlist_playlistitem USING btree (playlist_id);


--
-- Name: playlist_playlistitem_position_a4ed4327; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX playlist_playlistitem_position_a4ed4327 ON public.playlist_playlistitem USING btree ("position");


--
-- Name: playlist_playlistitem_track_id_91ff0168; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX playlist_playlistitem_track_id_91ff0168 ON public.playlist_playlistitem USING btree (track_id);


--
-- Name: ratings_alb_album_i_45d6f7_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX ratings_alb_album_i_45d6f7_idx ON public.ratings_albumrating USING btree (album_id, user_id);


--
-- Name: ratings_albumrating_album_id_6caccdc5; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX ratings_albumrating_album_id_6caccdc5 ON public.ratings_albumrating USING btree (album_id);


--
-- Name: ratings_albumrating_user_id_7bb516eb; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX ratings_albumrating_user_id_7bb516eb ON public.ratings_albumrating USING btree (user_id);


--
-- Name: ratings_tra_track_i_734176_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX ratings_tra_track_i_734176_idx ON public.ratings_trackrating USING btree (track_id, user_id);


--
-- Name: ratings_trackrating_track_id_4c2295b1; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX ratings_trackrating_track_id_4c2295b1 ON public.ratings_trackrating USING btree (track_id);


--
-- Name: ratings_trackrating_user_id_25285970; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX ratings_trackrating_user_id_25285970 ON public.ratings_trackrating USING btree (user_id);


--
-- Name: save_system_album_i_bffefe_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX save_system_album_i_bffefe_idx ON public.save_system_savedtrack USING btree (album_id, saved_at);


--
-- Name: save_system_owner_i_8e2423_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX save_system_owner_i_8e2423_idx ON public.save_system_savedalbum USING btree (owner_id, saved_at);


--
-- Name: save_system_owner_i_adb4a2_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX save_system_owner_i_adb4a2_idx ON public.save_system_savedtrack USING btree (owner_id, saved_at);


--
-- Name: save_system_savedalbum_original_album_id_8582ecb4; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX save_system_savedalbum_original_album_id_8582ecb4 ON public.save_system_savedalbum USING btree (original_album_id);


--
-- Name: save_system_savedalbum_owner_id_00ffd0ca; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX save_system_savedalbum_owner_id_00ffd0ca ON public.save_system_savedalbum USING btree (owner_id);


--
-- Name: save_system_savedtrack_album_id_f0bc968c; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX save_system_savedtrack_album_id_f0bc968c ON public.save_system_savedtrack USING btree (album_id);


--
-- Name: save_system_savedtrack_original_track_id_dbb54e09; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX save_system_savedtrack_original_track_id_dbb54e09 ON public.save_system_savedtrack USING btree (original_track_id);


--
-- Name: save_system_savedtrack_owner_id_5949c4a5; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX save_system_savedtrack_owner_id_5949c4a5 ON public.save_system_savedtrack USING btree (owner_id);


--
-- Name: socialaccount_socialaccount_user_id_8146e70c; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON public.socialaccount_socialaccount USING btree (user_id);


--
-- Name: socialaccount_socialapp_sites_site_id_2579dee5; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX socialaccount_socialapp_sites_site_id_2579dee5 ON public.socialaccount_socialapp_sites USING btree (site_id);


--
-- Name: socialaccount_socialapp_sites_socialapp_id_97fb6e7d; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX socialaccount_socialapp_sites_socialapp_id_97fb6e7d ON public.socialaccount_socialapp_sites USING btree (socialapp_id);


--
-- Name: socialaccount_socialtoken_account_id_951f210e; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON public.socialaccount_socialtoken USING btree (account_id);


--
-- Name: socialaccount_socialtoken_app_id_636a42d7; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON public.socialaccount_socialtoken USING btree (app_id);


--
-- Name: tracks_favo_owner_i_659563_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tracks_favo_owner_i_659563_idx ON public.tracks_favorite USING btree (owner_id, created_at);


--
-- Name: tracks_favo_owner_i_daf432_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tracks_favo_owner_i_daf432_idx ON public.tracks_favorite USING btree (owner_id, "position");


--
-- Name: tracks_favorite_owner_id_45bbbdc8; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tracks_favorite_owner_id_45bbbdc8 ON public.tracks_favorite USING btree (owner_id);


--
-- Name: tracks_favorite_track_id_9638e8d0; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tracks_favorite_track_id_9638e8d0 ON public.tracks_favorite USING btree (track_id);


--
-- Name: tracks_list_user_id_1e47ae_idx; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tracks_list_user_id_1e47ae_idx ON public.tracks_listen USING btree (user_id, played_at DESC);


--
-- Name: tracks_listen_track_id_1fa76259; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tracks_listen_track_id_1fa76259 ON public.tracks_listen USING btree (track_id);


--
-- Name: tracks_listen_user_id_166d07b1; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tracks_listen_user_id_166d07b1 ON public.tracks_listen USING btree (user_id);


--
-- Name: tracks_track_owner_id_77e2868e; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE INDEX tracks_track_owner_id_77e2868e ON public.tracks_track USING btree (owner_id);


--
-- Name: uniq_default_album_per_owner; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE UNIQUE INDEX uniq_default_album_per_owner ON public.album_album USING btree (owner_id) WHERE is_default;


--
-- Name: unique_primary_email; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE UNIQUE INDEX unique_primary_email ON public.account_emailaddress USING btree (user_id, "primary") WHERE "primary";


--
-- Name: unique_verified_email; Type: INDEX; Schema: public; Owner: neondb_owner
--

CREATE UNIQUE INDEX unique_verified_email ON public.account_emailaddress USING btree (email) WHERE verified;


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: album_album album_album_owner_id_c10e2982_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.album_album
    ADD CONSTRAINT album_album_owner_id_c10e2982_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: album_albumtrack album_albumtrack_album_id_39a93ea6_fk_album_album_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.album_albumtrack
    ADD CONSTRAINT album_albumtrack_album_id_39a93ea6_fk_album_album_id FOREIGN KEY (album_id) REFERENCES public.album_album(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: album_albumtrack album_albumtrack_track_id_01fed1ce_fk_tracks_track_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.album_albumtrack
    ADD CONSTRAINT album_albumtrack_track_id_01fed1ce_fk_tracks_track_id FOREIGN KEY (track_id) REFERENCES public.tracks_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: basket_savedbasket basket_savedbasket_user_id_f65b2fc1_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.basket_savedbasket
    ADD CONSTRAINT basket_savedbasket_user_id_f65b2fc1_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: basket_savedbasketitem basket_savedbasketit_basket_id_6d28029d_fk_basket_sa; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.basket_savedbasketitem
    ADD CONSTRAINT basket_savedbasketit_basket_id_6d28029d_fk_basket_sa FOREIGN KEY (basket_id) REFERENCES public.basket_savedbasket(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: basket_savedbasketitem basket_savedbasketitem_plan_id_c59761c6_fk_plans_plan_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.basket_savedbasketitem
    ADD CONSTRAINT basket_savedbasketitem_plan_id_c59761c6_fk_plans_plan_id FOREIGN KEY (plan_id) REFERENCES public.plans_plan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: checkout_order checkout_order_user_id_6420a551_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.checkout_order
    ADD CONSTRAINT checkout_order_user_id_6420a551_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: checkout_order checkout_order_user_profile_id_949184a7_fk_profile_p; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.checkout_order
    ADD CONSTRAINT checkout_order_user_profile_id_949184a7_fk_profile_p FOREIGN KEY (user_profile_id) REFERENCES public.profile_page_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: checkout_orderitem checkout_orderitem_order_id_b464a9c2_fk_checkout_order_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.checkout_orderitem
    ADD CONSTRAINT checkout_orderitem_order_id_b464a9c2_fk_checkout_order_id FOREIGN KEY (order_id) REFERENCES public.checkout_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: checkout_orderitem checkout_orderitem_plan_id_ff2838f0_fk_plans_plan_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.checkout_orderitem
    ADD CONSTRAINT checkout_orderitem_plan_id_ff2838f0_fk_plans_plan_id FOREIGN KEY (plan_id) REFERENCES public.plans_plan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cloud_connect_cloudaccount cloud_connect_cloudaccount_user_id_f5f6d781_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.cloud_connect_cloudaccount
    ADD CONSTRAINT cloud_connect_cloudaccount_user_id_f5f6d781_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cloud_connect_cloudfolderlink cloud_connect_cloudf_account_id_9fb6f663_fk_cloud_con; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.cloud_connect_cloudfolderlink
    ADD CONSTRAINT cloud_connect_cloudf_account_id_9fb6f663_fk_cloud_con FOREIGN KEY (account_id) REFERENCES public.cloud_connect_cloudaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cloud_connect_cloudfolderlink cloud_connect_cloudf_album_id_a27a14ef_fk_album_alb; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.cloud_connect_cloudfolderlink
    ADD CONSTRAINT cloud_connect_cloudf_album_id_a27a14ef_fk_album_alb FOREIGN KEY (album_id) REFERENCES public.album_album(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cloud_connect_cloudfilemap cloud_connect_cloudf_link_id_ada2d592_fk_cloud_con; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.cloud_connect_cloudfilemap
    ADD CONSTRAINT cloud_connect_cloudf_link_id_ada2d592_fk_cloud_con FOREIGN KEY (link_id) REFERENCES public.cloud_connect_cloudfolderlink(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cloud_connect_cloudfilemap cloud_connect_cloudfilemap_track_id_ad63ff25_fk_tracks_track_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.cloud_connect_cloudfilemap
    ADD CONSTRAINT cloud_connect_cloudfilemap_track_id_ad63ff25_fk_tracks_track_id FOREIGN KEY (track_id) REFERENCES public.tracks_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: follow_system_follow follow_system_follow_follower_id_05bd94c7_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.follow_system_follow
    ADD CONSTRAINT follow_system_follow_follower_id_05bd94c7_fk_auth_user_id FOREIGN KEY (follower_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: follow_system_follow follow_system_follow_following_id_bfeb7d58_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.follow_system_follow
    ADD CONSTRAINT follow_system_follow_following_id_bfeb7d58_fk_auth_user_id FOREIGN KEY (following_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: plans_usersubscription plans_usersubscription_plan_id_8fc03425_fk_plans_plan_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.plans_usersubscription
    ADD CONSTRAINT plans_usersubscription_plan_id_8fc03425_fk_plans_plan_id FOREIGN KEY (plan_id) REFERENCES public.plans_plan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: plans_usersubscription plans_usersubscription_user_id_e6b26fe1_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.plans_usersubscription
    ADD CONSTRAINT plans_usersubscription_user_id_e6b26fe1_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: playlist_playlist playlist_playlist_owner_id_1072c3f8_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.playlist_playlist
    ADD CONSTRAINT playlist_playlist_owner_id_1072c3f8_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: playlist_playlistitem playlist_playlistite_playlist_id_ce173e50_fk_playlist_; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.playlist_playlistitem
    ADD CONSTRAINT playlist_playlistite_playlist_id_ce173e50_fk_playlist_ FOREIGN KEY (playlist_id) REFERENCES public.playlist_playlist(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: playlist_playlistitem playlist_playlistitem_track_id_91ff0168_fk_tracks_track_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.playlist_playlistitem
    ADD CONSTRAINT playlist_playlistitem_track_id_91ff0168_fk_tracks_track_id FOREIGN KEY (track_id) REFERENCES public.tracks_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: profile_page_userprofile profile_page_userprofile_user_id_2eb37b4f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.profile_page_userprofile
    ADD CONSTRAINT profile_page_userprofile_user_id_2eb37b4f_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ratings_albumrating ratings_albumrating_album_id_6caccdc5_fk_album_album_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ratings_albumrating
    ADD CONSTRAINT ratings_albumrating_album_id_6caccdc5_fk_album_album_id FOREIGN KEY (album_id) REFERENCES public.album_album(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ratings_albumrating ratings_albumrating_user_id_7bb516eb_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ratings_albumrating
    ADD CONSTRAINT ratings_albumrating_user_id_7bb516eb_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ratings_trackrating ratings_trackrating_track_id_4c2295b1_fk_tracks_track_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ratings_trackrating
    ADD CONSTRAINT ratings_trackrating_track_id_4c2295b1_fk_tracks_track_id FOREIGN KEY (track_id) REFERENCES public.tracks_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ratings_trackrating ratings_trackrating_user_id_25285970_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.ratings_trackrating
    ADD CONSTRAINT ratings_trackrating_user_id_25285970_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: save_system_savedalbum save_system_savedalb_original_album_id_8582ecb4_fk_album_alb; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.save_system_savedalbum
    ADD CONSTRAINT save_system_savedalb_original_album_id_8582ecb4_fk_album_alb FOREIGN KEY (original_album_id) REFERENCES public.album_album(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: save_system_savedalbum save_system_savedalbum_owner_id_00ffd0ca_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.save_system_savedalbum
    ADD CONSTRAINT save_system_savedalbum_owner_id_00ffd0ca_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: save_system_savedtrack save_system_savedtra_original_track_id_dbb54e09_fk_tracks_tr; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.save_system_savedtrack
    ADD CONSTRAINT save_system_savedtra_original_track_id_dbb54e09_fk_tracks_tr FOREIGN KEY (original_track_id) REFERENCES public.tracks_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: save_system_savedtrack save_system_savedtrack_album_id_f0bc968c_fk_album_album_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.save_system_savedtrack
    ADD CONSTRAINT save_system_savedtrack_album_id_f0bc968c_fk_album_album_id FOREIGN KEY (album_id) REFERENCES public.album_album(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: save_system_savedtrack save_system_savedtrack_owner_id_5949c4a5_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.save_system_savedtrack
    ADD CONSTRAINT save_system_savedtrack_owner_id_5949c4a5_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_account_id_951f210e_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES public.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_app_id_636a42d7_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_site_id_2579dee5_fk_django_si; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc FOREIGN KEY (socialapp_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tracks_favorite tracks_favorite_owner_id_45bbbdc8_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tracks_favorite
    ADD CONSTRAINT tracks_favorite_owner_id_45bbbdc8_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tracks_favorite tracks_favorite_track_id_9638e8d0_fk_tracks_track_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tracks_favorite
    ADD CONSTRAINT tracks_favorite_track_id_9638e8d0_fk_tracks_track_id FOREIGN KEY (track_id) REFERENCES public.tracks_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tracks_listen tracks_listen_track_id_1fa76259_fk_tracks_track_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tracks_listen
    ADD CONSTRAINT tracks_listen_track_id_1fa76259_fk_tracks_track_id FOREIGN KEY (track_id) REFERENCES public.tracks_track(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tracks_listen tracks_listen_user_id_166d07b1_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tracks_listen
    ADD CONSTRAINT tracks_listen_user_id_166d07b1_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tracks_track tracks_track_owner_id_77e2868e_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: neondb_owner
--

ALTER TABLE ONLY public.tracks_track
    ADD CONSTRAINT tracks_track_owner_id_77e2868e_fk_auth_user_id FOREIGN KEY (owner_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: neondb_owner
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict Wsws3AjyHrO8TjJHNy7g3KT7lyhY3UKxZalOIyZxVoNp7NfJrFcMKRusArEpq7h

